# Generated by Django 5.2.5 on 2025-08-27 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 27, 18, 40)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
